# Generated by Django 5.2.10 on 2026-02-24 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ingest", "0003_seed_default_networks_from_env"),
        ("ingest", "0005_add_webhookdeliverylog_and_suspended_status"),
    ]

    operations = []
