# Generated by Django 5.2.10 on 2026-02-24 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingest", "0006_merge_20260224_1016"),
    ]

    operations = [
        migrations.AlterField(
            model_name="network",
            name="horizon_url",
            field=models.URLField(help_text="Horizon URL for this network"),
        ),
        migrations.AlterField(
            model_name="network",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Whether this network is actively indexed"
            ),
        ),
        migrations.AlterField(
            model_name="network",
            name="name",
            field=models.CharField(
                help_text="Short network name (e.g. 'testnet', 'mainnet')",
                max_length=64,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="network",
            name="network_passphrase",
            field=models.CharField(
                help_text="Stellar network passphrase for this network", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="network",
            name="rpc_url",
            field=models.URLField(help_text="Soroban RPC URL for this network"),
        ),
        migrations.AlterField(
            model_name="trackedcontract",
            name="network",
            field=models.ForeignKey(
                blank=True,
                help_text="Stellar network this contract belongs to",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contracts",
                to="ingest.network",
            ),
        ),
    ]
