# Generated by Django 5.2.10 on 2026-02-25 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0006_add_contract_timestamp_index'),
        ('ingest', '0007_alter_network_horizon_url_alter_network_is_active_and_more'),
    ]

    operations = [
    ]
