# Generated by Django 5.2.10 on 2026-03-29 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0025_merge_20260329_0125'),
        ('ingest', '0026_merge_20260329_0027'),
    ]

    operations = [
    ]
