# Generated by Django 5.2.10 on 2026-03-29 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0027_merge_20260329_2112'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallGraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graph_data', models.JSONField(help_text='Serialized DAG: nodes, edges, and metadata')),
                ('has_cycles', models.BooleanField(default=False, help_text='True if circular dependencies were detected during computation')),
                ('cycle_details', models.JSONField(blank=True, help_text='List of contract IDs involved in cycles', null=True)),
                ('computed_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContractDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_count', models.IntegerField(default=0, help_text='Total number of times this dependency has been observed')),
                ('first_call', models.DateTimeField(auto_now_add=True, help_text='Timestamp of the first observed call')),
                ('last_call', models.DateTimeField(auto_now=True, help_text='Timestamp of the most recent observed call')),
            ],
            options={
                'verbose_name_plural': 'Contract Dependencies',
            },
        ),
        migrations.RemoveIndex(
            model_name='trackedcontract',
            name='ingest_trac_evt_filter_type_idx',
        ),
        migrations.RenameIndex(
            model_name='ingesterror',
            new_name='ingest_inge_error_t_0174ca_idx',
            old_name='ingest_inge_error_t_b8e123_idx',
        ),
        migrations.RenameIndex(
            model_name='ingesterror',
            new_name='ingest_inge_created_fcf0ee_idx',
            old_name='ingest_inge_created_f8a456_idx',
        ),
        migrations.RenameIndex(
            model_name='trackedcontract',
            new_name='ingest_trac_alias_00de2f_idx',
            old_name='ingest_trac_alias_idx',
        ),
        migrations.AddField(
            model_name='callgraph',
            name='contract',
            field=models.OneToOneField(blank=True, help_text='The root contract for this graph (null for global graph)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='call_graph', to='ingest.trackedcontract'),
        ),
        migrations.AddField(
            model_name='contractdependency',
            name='callee',
            field=models.ForeignKey(help_text='The contract that was called', on_delete=django.db.models.deletion.CASCADE, related_name='called_by', to='ingest.trackedcontract'),
        ),
        migrations.AddField(
            model_name='contractdependency',
            name='caller',
            field=models.ForeignKey(help_text='The contract that initiated the call', on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='ingest.trackedcontract'),
        ),
        migrations.AlterUniqueTogether(
            name='contractdependency',
            unique_together={('caller', 'callee')},
        ),
    ]
